### ISSUE TITLE
Allow different versions of Python in EC2 agent

### ISSUE THREAD

**Issue by mtrivedi50** [runprism/nomad#3]
**Is your feature request related to a problem? Please describe.**
When running code on an EC2 agent, we can only run code using the instance's default Python3 version (usually 3.8 or 3.9). We want to be able to install new versions (3.10, 3.11, etc.) on the EC2 instance.

**Describe the solution you'd like**
Create a new key in the agent configuration called `python_version`:
```
my_cloud_agent:
  infra:
    type: ec2
    instance_type: t2.micro
    ami_image: ami-01c647eace872fc02
  python_version: 3.11                <-- new key!
  requirements: requirements.txt
  ...
```

**Describe alternatives you've considered**
N/A - this can block projects that rely on newer package versions / Python versions.

**Additional context**
None.
