### ISSUE TITLE
Docker on EC2 infra

### ISSUE THREAD

**Issue by mtrivedi50** [runprism/nomad#6]
**Is your feature request related to a problem? Please describe.**
- Creating an EC2 instance with a custom Python version can take a long time.
- It's difficult to replicate how your code would run in an EC2 instance locally.

**Describe the solution you'd like**
- Create a new `Infra` child class `DockerOnEc2`. This would correspond to:
```
my_cloud_agent:
  infra:
    type: docker-on-ec2
    base_image: python-3.10-slimbullseye
    dockerfile: Dockerfile   # optional
...
```
- If a user specifies this infrastructure type, then Nomad should:
1. Build a Docker image according to `Dockerfile` (if this isn't specified, then manually create the Dockerfile using the info from the configuration file)
2. Push the Docker image to ECS / Dockerhub (this may not be necessary)
3. Install Docker on the EC2 instance
4. Run the Docker image inside of EC2 after the instance is launched

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
